sudo: required

dist: trusty

language: node_js

node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 1f4ab3407ad054891aa532867c219b4768741db6
  on:
    branch: master
